"Enable Animals" = true
"Enable Blazes" = true
"Enable Creepers" = true
"Enable Drowneds" = true
"Enable Endermen" = true
"Enable Ghasts" = true
"Enable Pets" = true
"Enable Mobs" = true
"Enable Illagers" = true
"Enable Shulkers" = true
"Enable Bugs" = true
"Enable Skeletons" = true
"Enable Slimes" = true
"Enable Spiders" = true
"Enable Villagers" = true
"Enable Witches" = true
"Enable Warden" = true

